### ISSUE TITLE
"Inhalt kopieren" für das Ansicht-Modal

### ISSUE THREAD

**Issue by jweber-unibe** [ilub-unibe-ch/Hub2#2]
Lässt man sich einen XML-Eintrag anzeigen, wäre es nützlich, den dargestellten **Textinhalt** – ohne fummeliges und ggf. langwieriges Markieren mit der Maus – einfach **auswählen und/oder direkt kopieren** zu können (idealerweise wohl inkl. der Metadaten unterhalb der Modal-Überschrift "Details").

Ich könnte mir dazu gut einen **Button "Inhalt kopieren" (o.ä.) im Kopf des Modals** vorstellen. 

(Alternativ wäre 'notfalls' auch eine Modifikation zielführend, mit der man nach Markieren eines Wortes mit Ctrl+A den gesamten Textinhalt markieren und dann kopieren könnte – aktuell wird dabei die gesamte Seite markiert.)

**Comment by Amstutz** [comment]
machen wir, sobald es einen solchen button in ilias gibt. afaik, ein solcher ist in planung für den footer. im moment aber kein issue. bitte, solche punkte im supportmeeting ansprechen vor issue erstellen.
