### ISSUE TITLE
Löschen einer Sitzung führt zu Whoops

### ISSUE THREAD

**Issue by yvseiler** [ilub-unibe-ch/Hub2#3]
Wird eine bereits erstellte Sitzung nicht mehr geliefert im XML, so wird beim Einlesen (Re-Process) ein Whoops-Fehler ausgegeben:

Whoops\Exception\ErrorException thrown with message "Undefined array key "session_35555550_491192-HS2024-0""
 
Stacktrace:
#24 Whoops\Exception\ErrorException in /var/www/ilias-next/Customizing/global/plugins/Origins2/src/origins/session/unibeSessionOrigin.php:347
#23 ilErrorHandling:handlePreWhoops in /var/www/ilias-next/Customizing/global/plugins/Origins2/src/origins/session/unibeSessionOrigin.php:347
#22 iLub\Plugin\Origin\origins\session\unibeSessionOrigin:updateOpenCastEvent in /var/www/ilias-next/Customizing/global/plugins/Origins2/src/origins/session/unibeSessionOrigin.php:327
#21 iLub\Plugin\Origin\origins\session\unibeSessionOrigin:afterDeleteILIASObject in /var/www/ilias-next/Customizing/global/plugins/Services/Cron/CronHook/Hub2/src/Sync/Processor/ObjectSyncProcessor.php:229
#20 srag\Plugins\Hub2\Sync\Processor\ObjectSyncProcessor:process in /var/www/ilias-next/Customizing/global/plugins/Services/Cron/CronHook/Hub2/src/Sync/OriginSync.php:241
#19 srag\Plugins\Hub2\Sync\OriginSync:processObject in /var/www/ilias-next/Customizing/global/plugins/Services/Cron/CronHook/Hub2/src/Sync/OriginSync.php:172
#18 srag\Plugins\Hub2\Sync\OriginSync:execute in /var/www/ilias-next/Customizing/global/plugins/Services/Cron/CronHook/Hub2/src/Jobs/RunSync.php:177
#17 srag\Plugins\Hub2\Jobs\RunSync:run in /var/www/ilias-next/Customizing/global/plugins/Origins2/src/adminViews/AdHocDataView.php:262
#16 iLub\Plugin\Origin\adminViews\AdHocDataView:run in /var/www/ilias-next/Customizing/global/plugins/Origins2/src/adminViews/AdHocDataView.php:248
#15 iLub\Plugin\Origin\adminViews\AdHocDataView:adHocAsyncProcess in /var/www/ilias-next/Customizing/global/plugins/Origins2/src/adminViews/AdHocDataView.php:63
#14 iLub\Plugin\Origin\adminViews\AdHocDataView:executeCommand in /var/www/ilias-next/Customizing/global/plugins/Origins2/src/adminViews/MainView.php:53
#13 iLub\Plugin\Origin\adminViews\MainView:executeCommand in /var/www/ilias-next/Customizing/global/plugins/Services/Cron/CronHook/Hub2/classes/UI/CustomView/class.hub2CustomViewGUI.php:63
#12 hub2CustomViewGUI:executeCommand in /var/www/ilias-next/Services/UICore/classes/class.ilCtrl.php:203
#11 ilCtrl:forwardCommand in /var/www/ilias-next/Customizing/global/plugins/Services/Cron/CronHook/Hub2/classes/UI/class.hub2MainGUI.php:83
#10 hub2MainGUI:executeCommand in /var/www/ilias-next/Services/UICore/classes/class.ilCtrl.php:203
#9 ilCtrl:forwardCommand in /var/www/ilias-next/Customizing/global/plugins/Services/Cron/CronHook/Hub2/classes/class.ilHub2ConfigGUI.php:36
#8 ilHub2ConfigGUI:performCommand in /var/www/ilias-next/Services/Component/classes/class.ilPluginConfigGUI.php:88
#7 ilPluginConfigGUI:executeCommand in /var/www/ilias-next/Services/UICore/classes/class.ilCtrl.php:203
#6 ilCtrl:forwardCommand in /var/www/ilias-next/Services/Component/classes/Settings/class.ilObjComponentSettingsGUI.php:162
#5 ilObjComponentSettingsGUI:forwardConfigGUI in /var/www/ilias-next/Services/Component/classes/Settings/class.ilObjComponentSettingsGUI.php:119
#4 ilObjComponentSettingsGUI:executeCommand in /var/www/ilias-next/Services/UICore/classes/class.ilCtrl.php:203
#3 ilCtrl:forwardCommand in /var/www/ilias-next/Services/Administration/classes/class.ilAdministrationGUI.php:237
#2 ilAdministrationGUI:executeCommand in /var/www/ilias-next/Services/UICore/classes/class.ilCtrl.php:203
#1 ilCtrl:forwardCommand in /var/www/ilias-next/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /var/www/ilias-next/ilias.php:24

### Steps to reproduce

Betrifft diesen Kurs: https://ilias-next.unibe.ch/goto_ilias3_unibe_crs_2578205.html
(mittlerweile ist Sitzung 17.09.2024 gelöscht)

HUB ID 394023 > Aktionen > Re-Process

Folgender Teil im XML wird nicht mehr geliefert:
```
<einzelTermin>
            <id>35555550</id>
            <datum>17.09.2024</datum>
            <zeitVon>14:15</zeitVon>
            <zeitBis>16:00</zeitBis>
            <terminTyp>LV</terminTyp>
            <dozentenTermin>C8CC9FCE0F506999E0405C82790C2367</dozentenTermin>
            <teilnehmer>2B3EE9C2440E4223B700C155ECD7C2E6</teilnehmer>
        </einzelTermin>
```

**Comment by Amstutz** [comment]
Should be fixed, can you re-test? locally, not reproduceable.

**Comment by yvseiler** [comment]
is fixed, entry could be read in correctly. Session was deleted as requested.
